// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int number = Integer.parseInt(args[0]);
		int less = 0;
		int more = 0;
		for (int i = 0; i < number; i++){
			double random = Math.random();
			if(random > 0.5){
            	less++;
			}else{
				more++;
			}
		}
		if (more != 0){
			double c = (double)less/more;
			System.out.println("> 0.5: " + less + " times");
            System.out.println("<= 0.5: " + more + " times"); 
			System.out.println("Ratio: " + c);
		}else{
			System.out.println("> 0.5: " + less + " times");
            System.out.println("<= 0.5: " + more + " times");
		}

		}
	}
